### ISSUE TITLE
MatchComms Support

### ISSUE THREAD

**Issue by ddthj** [RLBot/core#11]
Would be nice to include matchcomms / tmcp support into the core. This would have the added benefit of making it team-specific so that each team only sees its own messages.

**Comment by ddthj** [comment]
Match-comms
Quick chat and match-comms could be combined
Implement using flatbuffers
Allow bots to print anything in “quick chat”
Spec/protocol could be based on TMCP

**Comment by VirxEC** [comment]
We decided to combine quick chats and match comms, implementing TMCP for it and using FlatBuffers + adding a `display_string` arg to keep the functionality of quick chats

**Comment by NicEastvillage** [comment]
What does "implementing TMCP for it" mean though? Will the flatbuffer message have the structure of a TMCP message? If so, that would make match-comms less versatile. E.g. rlbottraining is currently using match-comms to allow exercises to "brief" the bot before the exercise begins, and more. TMCP was designed for bot-bot communication specifically.

**Comment by VirxEC** [comment]
I wish you had brought this up in our meeting because FlatBuffers is pretty rigid and doesn't allow for arbitrary data to be passed around, which is why the TMCP spec was picked. Yes, it will make it less versatile by going with FlatBuffers.

**Comment by NicEastvillage** [comment]
There are definitely ideas from TMCP we can reuse. I imagine a match comms flatbuffer message to contain something this:
```
// The team receiving this message. -1 for both.
team:int,
// Index of bot that sent the message
from:int,
// Stuff that is displayed by our custom quick-chat rendering, i.e. what the humans see
display_string:string
// Content of the message. E.g. a TMCP action.
content:string
```
Do scripts have indexes? Maybe the `from` attribute should be the name instead. Or it could just be -1 to indicate that the message was not from a bot.

Btw. Now that we have the chance, we should also consider if "Match Comms" is the right name for this feature.

**Comment by ddthj** [comment]
> ```
> /// The team receiving this message. -1 for both.
> team:int,
> /// Index of bot that sent the message
> from:int,
> /// Stuff that is displayed by our custom quick-chat rendering, i.e. what the humans see
> display_string:string
> /// Content of the message, i.e. what bots see, e.g. the remainder of a TMCP message.
> content:string
> ```

I actually really like this. It's worth mentioning that we can determine the team and index of the bot that sent the message, so a bot doesn't necessarily need to send those (or if they do, core should probably verify their accuracy). I have mixed thoughts on the function of `team`. I like the thought of scripts being able to send messages to both teams, but I feel like a bot being able to target which team their message is received by is a little odd. I don't really want to place random inhibitions on this but limiting bots to their own team, and scripts to both teams, makes sense in my head.

I think the inclusion of `to` is something that would be better implemented at the protocol level. Sending messages to specific bots is a bit niche. 

I like the name MatchComms, but something as simple as Chat / Team Chat / Messaging would also be appropriate.

**Comment by NicEastvillage** [comment]
> we can determine the team and index of the bot that sent the message, so a bot doesn't necessarily need to send those

Yeah. An outgoing message just needs the content and then the core can add the messenger info when distributing it as in incoming message.

> I don't really want to place random inhibitions on this but limiting bots to their own team, and scripts to both teams, makes sense in my head.

Most of the time bots will send messages to their team, but I don't see why we would make it impossible to send to both. Then we will never get bots that react to the other team's trash-talk.

> Sending messages to specific bots is a bit niche.

Yes. I can't think of many scenarios where it will be relevant. On the other hand, without `to`, sending private messages to bots will be impossible through match comms.

**Comment by ViliamVadocz** [comment]
What about also have some common fields what messages can use so that bots can communicate more efficiently without as much parsing.

For example there could be a Vec3 field which could be used for position or direction. Another field could just be a float which can be used for time, or some other information.

**Comment by NicEastvillage** [comment]
I don't think the parsing convenience is worth the complexity added to the structures.

**Comment by swz-git** [comment]
I don't think we should have two separate protocols and "embed" the TMCP protocol inside of flatbuffers.

**Comment by ddthj** [comment]
> Yes. I can't think of many scenarios where it will be relevant. On the other hand, without `to`, sending private messages to bots will be impossible through match comms.

If you send a string that only the bot knows how to parse, you can kinda private message it
