### ISSUE TITLE
Allow all bots to possess a "Skill Level"

### ISSUE THREAD

**Issue by ddthj** [RLBot/core#14]
The union code just to support this one skill-level float for psyonix bots is so ugly... We could make everything make a lot more sense if all bots were passed this float. 

Aside from code aesthetics, this would allow people to implement skill-level sliders (I think a version of nexto does this?)

**Comment by VirxEC** [comment]
I would like an enum `PsyonixSkill` that’s `Beginner`, `Rookie`, `Pro`, or `AllStar`

**Comment by NicEastvillage** [comment]
Such an enum would still be a unique parameter to Psyonix bots which the issue raised - but definitely better than the current float, I agree.

**Comment by VirxEC** [comment]
As for passing values into bots, we could have an “env” header in tomls with key/value pairs and core could pass them as environment variables to the corresponding bots. This would be useful beyond just config values too.

**Comment by VirxEC** [comment]
Also I’m not personally concerned about the whole unique value thing. The above would be a new unique value for the RLBot type.

**Comment by redd-rl** [comment]
can skill levels be attached to bots based on their performance against a fixed target? so you could look at and match two similarly ranked bots based on their skill number, instead of having to rely on a two year old outdated posting or whatever else.

**Comment by NicEastvillage** [comment]
> can skill levels be attached to bots based on their performance against a fixed target? so you could look at and match two similarly ranked bots based on their skill number, instead of having to rely on a two year old outdated posting or whatever else.

No. Skill level isn't a rating of the bot. Is is currently a parameter passed to Psyonix bots to make them behave either as Allstar, Pro, or Rookie.

**Comment by redd-rl** [comment]
> > can skill levels be attached to bots based on their performance against a fixed target? so you could look at and match two similarly ranked bots based on their skill number, instead of having to rely on a two year old outdated posting or whatever else.
> 
> No. Skill level isn't a rating of the bot. Is is currently a parameter passed to Psyonix bots to make them behave either as Allstar, Pro, or Rookie.

i was referring to a separate value altogether, for all botpack bots.

**Comment by NicEastvillage** [comment]
Then that is a separate issue. You essentially ask if we can include bots' rating in the bot pack. Create an issue on the bot pack repo if you want to discuss such a feature.
