### ISSUE TITLE
Let users make and pick presets for Psyonix bots

### ISSUE THREAD

**Issue by NicEastvillage** [RLBot/core#38]
Some users like to run tournaments with Psyonix bots and sometimes change their name and appearance. In v4, the latter was technically possible, but a bit of a hassle to do. In v5 we should avoid hardcoding Psyonix bots too much. I propose the following features:
- Users can pick specific Psyonix bot name+loadout
  - in core/match toml: Matches can have (Psyonix) bots with specified/overridden name and loadout
  - in GUI: TBD. Maybe it should be possible to override any bots' name and appearance by right/double clicking a bot added to the current match before match start.
- Users can change the pool of names+loudouts used by Psyonix bots (less important, more advanced impl) 
  - We don't want users to accidentally delete the standard Psyonix bot loadouts, but they should be able to define a pool of loadouts that rlbot picks from. It should be easy to include/exclude standard loadouts and new custom loadouts in this pool. One solution could be a file that includes paths to the included loadouts.

**Comment by VirxEC** [comment]
We could read `config.toml` for Psyonix bots and allow setting the name, which if matching a preset, would load that preset. Also if a looks config is defined, we could just use that instead of any preset. This would be easy to implement.

The “adding to the preset pool” could also be faked by the gui with the above system.

**Comment by NicEastvillage** [comment]
I have thought about this a bit more. We also have users who want to troll their friends by renaming Nexto. So ideally, we should find a general solution that works with both custom and Psyonix bots. I imagine some kind of override field in the match config now.

What is `config.toml`? The one corresponding to `rlbot.cfg`?

Also related: #40

**Comment by VirxEC** [comment]
So it would look something like this:
```toml
[[cars]]
config = "greg.toml"
team = 0
type = "psyonix"
skill = "allstar"
```

**Comment by NicEastvillage** [comment]
We have settled on something akin to what Virx described above. The match settings (`rlbot.toml`) can override any bot's name and loadout. This enables the GUI (and other match starter tools) to control how (Psyonix) bots appear when using that tool. By default, core will select randomly from the standard loadouts used in the game when spawning Psyonix bots.
