### ISSUE TITLE
Inconsistency of fields values when they are irrelevant

### ISSUE THREAD

**Issue by NicEastvillage** [RLBot/core#47]
Noticed this detail on the wiki:
![billede](https://github.com/user-attachments/assets/6c98e020-39ad-4734-84b1-2238214c5df1)

It is inconsistent that one is using `0` and the other is using `-1` when not relevant. Can we make all such fields uses `-1` when irrelevant?

Edit: Note that the semantics of `dodge_timeout==0` is that the car is in the air and has either double jumped, dodged, or the time to do so has expired. But it does not affect the suggestion above.

**Comment by VirxEC** [comment]
yea

**Comment by VirxEC** [comment]
Closing as this was just an error in the old migration wiki. `demolished_timeout` was always `-1` when a player isn't demolished. The new migration wiki already has the correction information:

> `is_demolished` -> `demolished_timeout` - `-1` if the player is not demolished, otherwise the time remaining until the player respawns
