### ISSUE TITLE
Incorrect parsing of loadout.toml

### ISSUE THREAD

**Issue by NicEastvillage** [RLBot/core#51]
The orange Beast loadout seems to be using colors from the Blue loadout. All the pink details (decal, boost) should have been green.

![image](https://github.com/user-attachments/assets/f7c25ce5-5a0a-4a2a-853b-e33bd454f371)

Here's the loadout file: https://github.com/NicEastvillage/RLBot-Beast/blob/v5/beastbot/loadout.toml

**Comment by VirxEC** [comment]
Indeed, you seem to be right. Core is trying to read the `team` value from the wrong place, which always returns as null, which always defaults to blue.
