### ISSUE TITLE
DrawRect2D and DrawRect3D

### ISSUE THREAD

**Issue by NicEastvillage** [RLBot/core#53]
In v4 we can draw rectangles in 2d and 3d. These have not been implemented in v5 yet - probably due to their hacky implementation. Internally the rectangles are made drawing strings with transparent text and colored background. Those with closed-source access can search up `Rendering::makeFakeRectangleString()`.

For v5, we need to decide whether to add two new RenderMessages for Rect2D and Rect3D, or reuse the String2D and String3D types and move the `makeFakeRectangleString()` to the interfaces. The advantage of creating new rendering message types is that we get parity between the interfaces and no code duplication. So I suggest the former.

**Comment by VirxEC** [comment]
I dropped them because I didn't know of anyone that _used_ it, and it wasn't a part of the Psyonix API. That being said, it's not like it would be hard to implement.

**Comment by NicEastvillage** [comment]
This one is mine. I will implement it!

**Comment by VirxEC** [comment]
Just one thing, I saw in <https://github.com/RLBot/flatbuffers-schema/commits/rectangles/> that `String2D`'s `x` & `y` was converted into an integer instead of a float. Was this a mistake?

**Comment by NicEastvillage** [comment]
That is intentional since the 2d functions use pixel coordinates which is obvious when the type is integer. Do you think otherwise?

**Comment by VirxEC** [comment]
They do not use pixel coords, that was a limitation of the v4 api
