### ISSUE TITLE
In-game name of second copy of bot is call "(1)" not "(2)"

### ISSUE THREAD

**Issue by NicEastvillage** [RLBot/core#59]
![image](https://github.com/user-attachments/assets/aa1139cd-3f16-4130-955d-f738f6aeed72)

In v4, then second copy was called "(2)", third "(3)", etc.

**Comment by VirxEC** [comment]
<https://github.com/RLBot/core/blob/master/RLBotCS/ManagerTools/MatchStarter.cs#L105>
