### ISSUE TITLE
Loadout colors not applied correctly

### ISSUE THREAD

**Issue by NicEastvillage** [RLBot/core#60]
(Also reported by Rolv on Discord)

Orange Beast is supposed to be red with green dots:

![image](https://github.com/user-attachments/assets/66781bc4-496f-4ac6-a2c7-10ddde5361fd)

Blue Beast is supposed to be dark blue with purple dots:

![image](https://github.com/user-attachments/assets/9e32c2c2-93b4-4faf-8e29-994537a50f92)

Related #51

**Comment by VirxEC** [comment]
wrong issue closed, my bad

**Comment by VirxEC** [comment]
<https://github.com/NicEastvillage/RLBot-Beast/blob/v5/beastbot/loadout.toml>
your loadout file in incomplete. there are not paints specified here. please see [this example](https://github.com/VirxEC/rlbot-python-example/blob/master/src/loadout.toml)
